[package]
name = "pypi-import-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
content_inspector = "0.2.4"
indicatif = { version = "0.17.2", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.6.1"
tar = "0.4.38"
zip = { version = "0.6.3", features = ["deflate-zlib"] }
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }

[profile.release]
codegen-units = 1
lto = true