[package]
name = "pypi-import-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
flate2 = "1.0.25"
sha2 = { version = "0.10.6", features = ["asm"] }
tar = "0.4.38"
zip = { version = "0.6.3", features = ["flate2"] }
